1. Write a Python Program to Add Two Matrices?

In [ ]:
import numpy as np

matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix2 = [[1,2,3],[4,5,6],[7,8,9]]

result_matrix = [[0,0,0],[0,0,0],[0,0,0]]

for item1 in range(len(matrix1)):
  for item2 in range(len(matrix2)):
      result_matrix[item1][item2] = matrix1[item1][item2] + matrix2[item1][item2]

for item in result_matrix:
  print(item)

[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


2. Write a Python Program to Multiply Two Matrices?

In [ ]:
import numpy as np

matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix2 = [[1,2,3],[4,5,6],[7,8,9]]

result_matrix = [[0,0,0],[0,0,0],[0,0,0]]

for item1 in range(len(matrix1)):
  for item2 in range(len(matrix2[0])):
    for item3 in range(len(matrix2)):
      result_matrix[item1][item2] += matrix1[item1][item3] * matrix2[item3][item2]

for item in result_matrix:
  print(item)

[30, 36, 42]
[66, 81, 96]
[102, 126, 150]


3. Write a Python Program to Transpose a Matrix?

In [1]:
import numpy as np
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
print(np.transpose(matrix1))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [8]:
list1 = ['e','r','w','a','d','q','c','t','b','o','y','o']
list1.sort()
print(list1)


['a', 'b', 'c', 'd', 'e', 'o', 'o', 'q', 'r', 't', 'w', 'y']


5. Write a Python Program to Remove Punctuation From a String?

In [21]:
string  = '''This is an ! INeuron %  Assignment. Further,I'wll'''
punctuation_string = '''!@#$%^&*(){]{']<>,.?/'''
for item in string:
  if item in punctuation_string:
    string = string.replace(item,"")
print(string)

This is an  INeuron   Assignment FurtherIwll
